17-12-2020;13:58:43 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;13:58:46 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
17-12-2020;13:58:48 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
17-12-2020;13:58:48 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
17-12-2020;13:58:49 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
17-12-2020;14:02:28 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1608210148736, current=DOWN, previous=UP]
17-12-2020;14:02:28 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: org.apache.http.NoHttpResponseException: localhost:8761 failed to respond
17-12-2020;14:02:28 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: org.apache.http.client.ClientProtocolException
17-12-2020;14:02:28 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_RAIFFEISEN/host.docker.internal:raiffeisen:8090 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17-12-2020;14:02:28 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17-12-2020;14:09:45 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:09:48 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
17-12-2020;14:09:50 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
17-12-2020;14:09:50 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
17-12-2020;14:09:51 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
17-12-2020;14:13:23 WARN  c.p.r.s.i.TransactionService.pay:58 - ["Raiffeisen Bank"] account not found [Wilfred Zaha]
17-12-2020;14:13:23 WARN  c.p.r.s.i.TransactionService.pay:61 - ["Raiffeisen Bank"] cross bank transaction [Wilfred Zaha],[acq-orderId=1]
17-12-2020;14:13:27 WARN  c.p.r.s.i.TransactionService.pay:67 - ["Raiffeisen Bank"] account not found [Wilfred Zaha]
17-12-2020;14:14:47 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1608210887038, current=DOWN, previous=UP]
17-12-2020;14:14:47 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: org.apache.http.NoHttpResponseException: localhost:8761 failed to respond
17-12-2020;14:14:47 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.SocketException: Connection reset
17-12-2020;14:14:47 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_RAIFFEISEN/host.docker.internal:raiffeisen:8090 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17-12-2020;14:14:47 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17-12-2020;14:35:29 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
17-12-2020;14:35:32 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
17-12-2020;14:35:33 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
17-12-2020;14:35:33 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
17-12-2020;14:35:34 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
17-12-2020;14:38:12 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1608212292685, current=DOWN, previous=UP]
17-12-2020;14:38:12 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: org.apache.http.NoHttpResponseException: localhost:8761 failed to respond
17-12-2020;14:38:12 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: org.apache.http.NoHttpResponseException: localhost:8761 failed to respond
17-12-2020;14:38:12 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_RAIFFEISEN/host.docker.internal:raiffeisen:8090 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17-12-2020;14:38:12 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
