05-01-2021;15:51:51 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "bank" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;15:51:54 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
05-01-2021;15:51:58 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;15:51:58 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;15:52:00 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
05-01-2021;15:52:06 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;15:52:06 WARN  c.n.d.DiscoveryClient.get:303 - Using default backup registry implementation which does not do anything.
05-01-2021;15:52:07 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1609858327838, current=DOWN, previous=UP]
05-01-2021;15:52:10 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;15:52:10 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_BANK/host.docker.internal:bank:8095 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;15:52:10 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;15:52:14 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;15:52:14 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_BANK/host.docker.internal:bank:8095 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;15:52:14 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;15:52:15 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;16:11:37 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:39 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "bank" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:11:40 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
05-01-2021;16:11:42 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;16:11:42 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;16:11:44 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
05-01-2021;16:11:46 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1609859506694, current=DOWN, previous=UP]
05-01-2021;16:24:06 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "bank" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:24:09 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
05-01-2021;16:24:12 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;16:24:12 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;16:24:14 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
05-01-2021;16:24:22 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;16:24:22 WARN  c.n.d.DiscoveryClient.get:303 - Using default backup registry implementation which does not do anything.
05-01-2021;16:24:24 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1609860264114, current=DOWN, previous=UP]
05-01-2021;16:24:26 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;16:24:26 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_BANK/host.docker.internal:bank:8095 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;16:24:26 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;16:24:30 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;16:24:30 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_BANK/host.docker.internal:bank:8095 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;16:24:30 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;16:24:31 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;16:31:39 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "bank" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;16:31:42 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
05-01-2021;16:31:46 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;16:31:46 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;16:31:48 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
05-01-2021;16:31:52 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1609860712349, current=DOWN, previous=UP]
05-01-2021;17:02:09 WARN  o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration.openEntityManagerInViewInterceptor:220 - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "account" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "customer_account" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "merchant_order" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "payment_request" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "seller_account" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - relation "transaction" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "account" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "address" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "bank" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "customer_account" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "merchant_order" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "order_counter" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "payment_request" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "seller_account" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "transaction" does not exist, skipping
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:230 - SQL Warning Code: 0, SQLState: 00000
05-01-2021;17:02:14 WARN  o.h.e.j.s.SqlExceptionHelper.logWarning:231 - table "url_responder" does not exist, skipping
05-01-2021;17:02:19 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;17:02:19 WARN  c.n.c.s.URLConfigurationSource.<init>:121 - No URLs will be polled as dynamic configuration sources.
05-01-2021;17:02:21 WARN  o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger.logWarning:86 - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
05-01-2021;17:02:27 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;17:02:27 WARN  c.n.d.DiscoveryClient.get:303 - Using default backup registry implementation which does not do anything.
05-01-2021;17:02:29 WARN  c.n.d.DiscoveryClient.notify:1351 - Saw local status change event StatusChangeEvent [timestamp=1609862549078, current=DOWN, previous=UP]
05-01-2021;17:02:31 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;17:02:31 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_BANK/host.docker.internal:bank:8095 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;17:02:31 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;17:02:35 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
05-01-2021;17:02:35 WARN  c.n.d.DiscoveryClient.register:875 - DiscoveryClient_BANK/host.docker.internal:bank:8095 - registration failed Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;17:02:35 WARN  c.n.d.InstanceInfoReplicator.run:125 - There was a problem with the instance info replicator
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:873)
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05-01-2021;17:02:36 WARN  c.n.d.s.t.d.RetryableEurekaHttpClient.execute:130 - Request execution failed with message: java.net.ConnectException: Connection refused: connect
